### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by rsp4jack** [lintx/YinwuChat-Bungeecord#4]
一直报MySQL的错
[21:06:24 ERROR]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'chat.chat_token' doesn't exist
[21:06:24 ERROR]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:06:24 ERROR]:       at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[21:06:24 ERROR]:       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:06:24 ERROR]:       at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:06:24 ERROR]:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[21:06:24 ERROR]:       at com.mysql.jdbc.Util.getInstance(Util.java:408)
[21:06:24 ERROR]:       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[21:06:24 ERROR]:       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[21:06:24 ERROR]:       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[21:06:24 ERROR]:       at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[21:06:24 ERROR]:       at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[21:06:24 ERROR]:       at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[21:06:24 ERROR]:       at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
[21:06:24 ERROR]:       at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1251)
[21:06:24 ERROR]:       at org.lintx.yinwuchat.bungeecord.MySql.execute(MySql.java:173)
[21:06:24 ERROR]:       at org.lintx.yinwuchat.bungeecord.Yinwuchat.clearExpireToken(Yinwuchat.java:107)
[21:06:24 ERROR]:       at org.lintx.yinwuchat.bungeecord.Yinwuchat.loadConfig(Yinwuchat.java:72)
[21:06:24 ERROR]:       at org.lintx.yinwuchat.bungeecord.Yinwuchat.onEnable(Yinwuchat.java:181)
[21:06:24 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:283)
[21:06:24 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
[21:06:24 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[21:06:24 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by rsp4jack** [comment]
没看readme
